package com.example.springbootdemo.model;
import java.io.Serializable;
import lombok.Data;


/**
 *   学生信息表
 * 
 * @mbg.generated
 */
@Data
public class Student implements Serializable {
    private static final long serialVersionUID = 1L;

    private Integer ID;

    /**
     * 姓
     *
     * @mbg.generated
     */
    private String NAME;

    /**
     * 年
     *
     * @mbg.generated
     */
    private Integer AGE;

    /**
     * 性别 1男2女
     *
     * @mbg.generated
     */
    private Boolean SEX;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns 
     *
     * @return the value of student.ID
     *
     * @mbg.generated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param ID the value for student.ID
     *
     * @mbg.generated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.NAME
     *
     * @return the value of student.NAME
     *
     * @mbg.generated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.NAME
     *
     * @param NAME the value for student.NAME
     *
     * @mbg.generated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.AGE
     *
     * @return the value of student.AGE
     *
     * @mbg.generated
     */
    public Integer getAGE() {
        return AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.AGE
     *
     * @param AGE the value for student.AGE
     *
     * @mbg.generated
     */
    public void setAGE(Integer AGE) {
        this.AGE = AGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.SEX
     *
     * @return the value of student.SEX
     *
     * @mbg.generated
     */
    public Boolean getSEX() {
        return SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.SEX
     *
     * @param SEX the value for student.SEX
     *
     * @mbg.generated
     */
    public void setSEX(Boolean SEX) {
        this.SEX = SEX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated
     */
    @Override
public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" [");
    sb.append("Hash = ").append(hashCode());
    sb.append(", serialVersionUID=").append(serialVersionUID);
    sb.append(", ID=").append(ID);
    sb.append(", NAME=").append(NAME);
    sb.append(", AGE=").append(AGE);
    sb.append(", SEX=").append(SEX);
    sb.append("]");
    return sb.toString();
}
}