spring:
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/firstdatasource?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      data-source-properties:
        nullCatalogMeansCurrent: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 是否触发回调方法
    # NONE值是禁用发布确认模式，是默认值
    # CORRELATED值是发布消息成功到交换器后会触发回调方法，如1示例
    # SIMPLE值经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;
    publisher-confirm-type: correlated
    # 发送者开启 return 确认机制
    publisher-returns: true
    #消费只开始手动确认模式 注意：千万不要忘记手动ACK确认，否则消息一直存在循环消费
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
