server:
  port: 8222

spring:
  application:
    name: my-first-springboot
  profiles:
    #指定活动的配置文件
    active: dev
  autoconfigure:
    exclude:
      # 禁用Redis(如使用Redis请删除或者注释下面两行)
      #- org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      #- org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      # 禁用数据源(如使用数据源请删除或者注释下面两行)
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      #- org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      #- org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

mybatis:
  type-aliases-package: com.example.springbootdemo.model
  mapper-locations: classpath:**/mapper/**/*.xml
